Fill in the Reg C gaps
cfpb/regulations-xml pull request #19
Opened 2017-08-25 20:58 UTC by grapesmoker

This PR adds the Reg C notices that were missing from the initial build of Reg C because we didn't have the diff capability yet. The notice 2015-26607 contains three separate effective dates, and those are broken out into three separate notice files, with the appropriate dependencies on prior versions. The regulation versions compiled with those notices are also added.

2017-08-25 21:01 UTC, chosak commented
@grapesmoker would you mind resolving these conflicts before I review this?

2017-08-25 21:04 UTC, grapesmoker commented
I'm trying but I'm not sure what they are. I was able to merge master into the branch without any problems...

2017-08-25 21:17 UTC, grapesmoker commented
The problem is that it won't show me what the conflicts are; when I try to merge master into the branch, I don't actually see any conflicts there.

2017-08-25 21:31 UTC, chosak commented
I can reproduce the conflicts locally:

```sh
$ git fetch
$ git checkout reg-c-gaps
$ git merge origin/master
```

2017-08-25 21:33 UTC, grapesmoker commented
Last time I did that it didn't work, but now it does. [shakes fist] GIIITTTTTT! I'll fix and try again.

2017-08-25 22:35 UTC, grapesmoker commented
Ok, I think I have fixed all the conflicts.

2017-08-29 16:50 UTC, chosak requested changes

2017-08-29 16:50 UTC, chosak commented on notice/1003/2015-26607_20200101.xml
> +<notice xmlns="eregs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="eregs https://raw.githubusercontent.com/cfpb/regulations-schema/master/src/eregs.xsd">
This line fails RegML schema validation, it should be `xsi:schemaLocation` instead of `schemaLocation`.

2017-08-29 17:26 UTC, grapesmoker commented
oops

2017-08-29 17:29 UTC, chosak approved these changes
Thanks; these content changes are far too complex to go through line-by-line but I don't see anything major jumping out at me in the structure of the changes.

2017-08-29 17:34 UTC, grapesmoker commented
Yeah, there's nothing really major here. It's just the same content that was in the regulation files but broken out into notices.

2017-08-29 17:34 UTC, merged